version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: esf_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5


  auth-service:
    build: ./auth-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/esf_db
    ports:
      - "8001:8001"

  esf-service:
    build: ./esf-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/esf_db
      - GNS_PROXY=http://gns-proxy:8003/gns/receive
      - AUTH_SERVICE=http://auth-service:8001
    ports:
      - "8002:8002"

  gns-proxy:
    build: ./gns-proxy
    ports:
      - "8003:8003"

volumes:
  pgdata:
